workflows:
  android-workflow:
    name: Build Vinyl Identifier APK
    max_build_duration: 15
    environment:
      flutter: stable
      android_signing:
        use_android_signing: false
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
