name: record_magic
description: A Flutter app to identify vinyl records from video
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5
  http: ^0.13.6
  path_provider: ^2.1.2
  path: ^1.9.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
